<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DodosPhotoSaver</AssemblyName>
    <Product>Dodo's Photo Saver</Product>
    <Version>0.1.1</Version>

    <ApplicationDefaultFont>Segoe UI, 10pt</ApplicationDefaultFont>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediaDevices" Version="1.10.0" />
    <PackageReference Include="MetadataExtractor" Version="2.8.1" />
  </ItemGroup>

</Project>
